import SimpleSidebar from '../Components/sidebar'
import { Providers } from './providers'

export const metadata = {
  title: 'Weavers',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body><Providers>
        <SimpleSidebar>{children}</SimpleSidebar>
        </Providers></body>
    </html>
  )
}

